Add check for rccl-tests using the `aws-ofi-plugin` with singularity
Lumi-supercomputer/lumi-reframe-tests pull request #13
Opened 2022-08-10 08:11 UTC by rsarm

2022-08-10 09:00 UTC, rsarm commented
In some case openmpi might need to be replaced by the host's with something like this
```python
# in the class rccl_tests_allreduce
self.variables = {
    'NCCL_DEBUG': 'INFO',
    'NCCL_NET_GDR_LEVEL': '3',
    'SINGULARITY_BIND': '/path/to/host/openmpi-4.1.2-install:/ext_openmpi,$SINGULARITY_BIND',
    'SINGULARITYENV_LD_LIBRARY_PATH': f'/opt/rocm-5.0.1/lib:'
                                      f'{self.rccl_dir}/rccl/build/:'
                                      f'{self.aws_plugin_dir}/aws-ofi-rccl/install/lib:'
                                      '/opt/cray/xpmem/2.3.2-2.2_6.13__g93dd7ee.shasta/lib64:'
                                      '/ext_openmpi/lib:'
                                      '$SINGULARITYENV_LD_LIBRARY_PATH'
}        
```

2022-10-19 15:04 UTC, mszpindler commented on checks/libs/rccl/check_rccl-tests-sing.py
> +    executable = f'git clone -b cxi git@github.com:ROCmSoftwarePlatform/{repo_name}.git'  # noqa: E501
The same here:
git clone -b develop https://github.com/ROCmSoftwarePlatform/{repo_name}.git

2022-10-19 15:16 UTC, mszpindler commented
The module `singularity-bindings/system-cpeGNU-21.08` requires specific environment. With which combination of `LUMI` and `partition` modules your were testing?

2022-10-21 09:46 UTC, rsarm commented
Now for the module `singularity-bindings/system-cpeGNU-21.08-noglibc`, we get the cpe version from the systems default. That depends on this PR https://github.com/reframe-hpc/reframe/pull/2644.

2022-10-21 14:31 UTC, mszpindler commented
I can't get it to work because of `singularity-bindings/system-cpeGNU-22.08-noglibc` module. Although I have it installed from your PR I still keep receiving:
`Reason: environ error: could not execute module operation: command '/usr/share/lmod/lmod/libexec/lmod python show singularity-bindings/system-cpeGNU-22.08-noglibc' failed with exit code 1:`
on the `build_aws_plugin` step.

2022-10-25 08:47 UTC, mszpindler commented
> * needs the non-libgc version of the `singularity-bindings/system-cpeGNU-22.06` module ([Add singularity bindings with no glibc mount LUMI-EasyBuild-contrib#50](https://github.com/Lumi-supercomputer/LUMI-EasyBuild-contrib/pull/50))

https://github.com/Lumi-supercomputer/LUMI-EasyBuild-contrib/pull/51 needed

2022-10-25 11:02 UTC, mszpindler approved these changes

2022-10-25 11:03 UTC, mszpindler commented on checks/libs/rccl/check_rccl-tests-sing.py
> +        return sn.path_isfile(f'{lib_dir}/install/lib/librccl-net.so.0.0.0')
return sn.path_isfile(f'{lib_dir}/librccl-net.so.0.0.0')

2022-10-25 11:03 UTC, mszpindler commented on checks/libs/rccl/check_rccl-tests-sing.py
> +        return sn.path_isfile(f'{lib_dir}/install/lib/librccl-net.so.0.0.0')
This is corrects path here.

2022-10-25 11:18 UTC, mszpindler commented on checks/libs/rccl/check_rccl-tests-sing.py
> +        return sn.assert_eq(num_binaries, 11)
There are 10 binaries built actually.

2022-10-25 11:19 UTC, mszpindler requested changes
Need to update `build_aws_plugin` and `build_rccl_tests` sanity functions.

2022-10-25 15:26 UTC, rsarm commented on checks/libs/rccl/check_rccl-tests-sing.py
> +        self.job.launcher = getlauncher('mpirun')()
Now with the new singularity binding modules the test is passing :)

2022-10-26 10:41 UTC, mszpindler approved these changes

2022-11-03 06:47 UTC, merged